# Generated by Django 6.1.1 on 2026-10-05 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('highest_qualification', models.CharField(blank=True, max_length=200)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('field_of_study', models.CharField(blank=True, max_length=200)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('subjects', models.TextField(blank=True)),
                ('grade_levels', models.CharField(blank=True, max_length=200)),
                ('employment_type', models.CharField(blank=True, max_length=100)),
                ('preferred_location', models.CharField(blank=True, max_length=200)),
                ('willing_to_relocate', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
